version: '3.4'

name: employee-manager
services:
  employee-manager-db:
    container_name: employee-manager-db
    image: employee-manager-db
    command: mysqld --default_authentication_plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: ../db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: basic_employee_manager
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - employee-manager-network
      
  employee-manager:
    container_name: employee-manager-api
    image: employee-manager
    build:
      context: .
      dockerfile: EmployeeManager/Dockerfile
    restart: always
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 55000:8080
      - 55001:8081
    depends_on:
      - employee-manager-db
    networks:
      - employee-manager-network
networks:
  employee-manager-network:
    driver: bridge