CREATE TABLE IF NOT EXISTS `Employees` (
  `Id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(60) NOT NULL,
  `LastName` VARCHAR(60) NOT NULL,
  `Email` VARCHAR(40) NOT NULL,
  `DocumentNumber` VARCHAR(20) NOT NULL UNIQUE,
  `ManagerId` BIGINT(20) NULL DEFAULT NULL,
  `Role` INT(2) NOT NULL,
  `BirthDate` DATETIME(6) NOT NULL,
  `Active` BIT(1) NOT NULL,
  PRIMARY KEY (`Id`),
  FOREIGN KEY (`ManagerId`) REFERENCES `Employees`(`Id`)
)