CREATE TABLE IF NOT EXISTS `Users` (
  `Id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UserDocument` VARCHAR(20) NOT NULL UNIQUE,
  `Password` VARCHAR(130) NOT NULL,
  `FullName` VARCHAR(120) NOT NULL,
  `RefreshToken` VARCHAR(500) NULL DEFAULT '0',
  `RefreshTokenExpiryTime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Id`)
)
ENGINE=InnoDB DEFAULT CHARSET=latin1;